
    
	<?php  $editRecord=$block->getEditRecord();?>
    <div id="login-form">
        <h1>Edit User</h1>
        <fieldset>
            <form action="<?php echo $block->getUrl('testcrud/index/save'); ?>" method="post">
				<input type="text" name="id" value="<?php echo $editRecord['id']; ?>" readonly>
				<input type="text" name="fname" required value="<?php echo $editRecord['fname']; ?>" onBlur="if(this.value=='')this.value='<?php echo $editRecord['fname']; ?>'" onFocus="if(this.value=='<?php echo $editRecord['fname']; ?>')this.value='' ">
                <input type="text" name="lname" required value="<?php echo $editRecord['lname']; ?>" onBlur="if(this.value=='')this.value='<?php echo $editRecord['lname']; ?>'" onFocus="if(this.value=='<?php echo $editRecord['lname']; ?>')this.value='' ">
                <input type="text" name="email" required value="<?php echo $editRecord['email']; ?>" onBlur="if(this.value=='')this.value='<?php echo $editRecord['email']; ?>'" onFocus="if(this.value=='<?php echo $editRecord['email']; ?>')this.value='' ">
                <footer class="clearfix">
                    <p><div align="right">
					<input type="submit" value="Update" class="action primary"></div><a href="<?php echo $block->getUrl('testcrud/index/index'); ?>">Back?</a>
					</p>
                </footer>
            </form>
        </fieldset>

    </div>
