
<h1>Users Table</h1>
    
<table>
     <tr>
          <th>Id</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>E-mail</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th colspan="2"> Action <div><a class="action primary" href="<?php echo $block->getUrl('testcrud/index/insert');?> ">Add Record</a></div></th>
     </tr>
 
     <?php
          $collection = $block->getCollection();
          foreach($collection->getItems() as $item){  ?>
     <tr>
          <td><?php echo $item->getData('id'); ?></td>
          <td><?php echo $item->getData('fname'); ?></td>
          <td><?php echo $item->getData('lname'); ?></td>
          <td><?php echo $item->getData('email'); ?></td>
          <td><?php echo $item->getData('cdate'); ?></td>
          <td><?php echo $item->getData('udate'); ?></td>
          <td><a href="<?php echo $block->getUrl('testcrud/index/edit').'?id='.$item->getData('id'); ?>" class="action primary"> Edit </a></td>
          <td><a href="<?php echo $block->getUrl('testcrud/index/delete').'?id='.$item->getData('id'); ?>" class="action primary"> Delete </a></td>
     </tr>
     <?php } ?>
</table>