
   
    <div id="login-form">
        <h1>Insert User</h1>

        <fieldset>
            <form action="<?php echo $block->getUrl(/* Generate url by route and parameters
     											* @param   string $route
     											* @param   array $params
     											* @return  string*/
												 'testcrud/index/save'); ?>" method="post">
                <input type="text" name="fname" required value="First Name" onBlur="if(this.value=='')this.value='First Name'" onFocus="if(this.value=='First Name')this.value='' ">
                <input type="text" name="lname" required value="Last Name" onBlur="if(this.value=='')this.value='Last Name'" onFocus="if(this.value=='Last Name')this.value='' ">
                <input type="text" name="email" required value="E-mail" onBlur="if(this.value=='')this.value='E-mail'" onFocus="if(this.value=='E-mail')this.value='' ">
                <footer class="clearfix">
                    <p><div align="right">
					    <input type="submit" value="Insert" class="action primary"></div><a href="<?php echo $block->getUrl('testcrud/index/index'); ?>" >Back?</a>
					</p>
                </footer>
            </form>
        </fieldset>

    </div>
